; Límites de carga de archivos - SIG
upload_max_filesize = 8M
post_max_size = 12M

; Tiempo suficiente para conexiones lentas
max_execution_time = 120
max_input_time = 120

; Memoria PHP
memory_limit = 128M
